package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/joa23/linear-cli/internal/linear/core"
	"github.com/joa23/linear-cli/internal/token"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// ProjectConfig represents the .linear.yaml config file
type ProjectConfig struct {
	Workspace string `yaml:"workspace,omitempty"`
	Team      string `yaml:"team"`
	Project   string `yaml:"project,omitempty"`
}

const configFileName = ".linear.yaml"

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Initialize Linear for this project",
		Long: `Initialize Linear for this project directory.

This command will:
1. Let you select a default team for this project
2. Create a .linear.yaml config file
3. Add usage instructions to AGENTS.md and CLAUDE.md`,
		Annotations: map[string]string{"skipAuth": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInit()
		},
	}
}

func runInit() error {
	fmt.Println("Linear Project Initialization")
	fmt.Println("==============================")
	fmt.Println()

	// Determine workspace to use.
	// Only use explicit sources here (--workspace flag or .linear.yaml) — skip auto-select
	// so the picker below always gets a chance to run when workspaces are available.
	p := resolveWorkspaceExplicit()
	workspacePicked := p != ""

	// If no explicit workspace, let the user pick from available workspaces.
	if !workspacePicked {
		workspaces := discoverWorkspaces()
		if len(workspaces) > 1 {
			p = promptWorkspaceSelection(workspaces)
			workspacePicked = true
			fmt.Println()
		} else if len(workspaces) == 1 {
			p = workspaces[0]
			workspacePicked = true
			if p != "" {
				fmt.Printf("Using workspace: %s\n\n", p)
			}
		}
	}

	// Check authentication
	client, err := initializeClient(p)
	if err != nil {
		fmt.Printf("❌ %v\n", err)
		return nil
	}

	// Get teams
	teams, err := client.GetTeams()
	if err != nil {
		return fmt.Errorf("failed to get teams: %w", err)
	}

	if len(teams) == 0 {
		fmt.Println("No teams found in your Linear workspace.")
		return nil
	}

	// Show teams and let user pick
	fmt.Println("Available teams:")
	fmt.Println()
	for i, team := range teams {
		fmt.Printf("  %d. %s (%s)\n", i+1, team.Name, team.Key)
	}
	fmt.Println()

	// Get selection
	var selectedTeam core.Team
	if len(teams) == 1 {
		selectedTeam = teams[0]
		fmt.Printf("Using team: %s (%s)\n", selectedTeam.Name, selectedTeam.Key)
	} else {
		fmt.Print("Select team [1]: ")
		reader := bufio.NewReader(os.Stdin)
		input, _ := reader.ReadString('\n')
		input = strings.TrimSpace(input)

		selection := 1
		if input != "" {
			selection, err = strconv.Atoi(input)
			if err != nil || selection < 1 || selection > len(teams) {
				return fmt.Errorf("invalid selection")
			}
		}
		selectedTeam = teams[selection-1]
	}

	fmt.Println()

	// Optionally set workspace
	workspaceName := p
	if workspacePicked && p == "" {
		// User explicitly picked the default workspace from the picker;
		// record it so the choice is visible in .linear.yaml.
		workspaceName = "default"
	} else if !workspacePicked {
		fmt.Print("Default workspace (leave empty for none): ")
		reader := bufio.NewReader(os.Stdin)
		wInput, _ := reader.ReadString('\n')
		workspaceName = strings.TrimSpace(wInput)
	}

	// Write config file
	projConfig := ProjectConfig{Team: selectedTeam.Key, Workspace: workspaceName}
	if err := writeConfig(projConfig); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}
	if workspaceName != "" {
		fmt.Printf("✅ Created %s (team: %s, workspace: %s)\n", configFileName, selectedTeam.Key, workspaceName)
	} else {
		fmt.Printf("✅ Created %s (team: %s)\n", configFileName, selectedTeam.Key)
	}

	// Write to AGENTS.md
	if err := appendToAgentFile("AGENTS.md", selectedTeam.Key); err != nil {
		fmt.Printf("⚠️  Could not update AGENTS.md: %v\n", err)
	} else {
		fmt.Println("✅ Updated AGENTS.md")
	}

	// Write to CLAUDE.md
	if err := appendToAgentFile("CLAUDE.md", selectedTeam.Key); err != nil {
		fmt.Printf("⚠️  Could not update CLAUDE.md: %v\n", err)
	} else {
		fmt.Println("✅ Updated CLAUDE.md")
	}

	fmt.Println()
	fmt.Println("Done! You can now use Linear commands without specifying --team.")
	fmt.Println()
	fmt.Println("Try:")
	fmt.Printf("  linear issues list\n")
	fmt.Printf("  linear cycles list\n")
	fmt.Printf("  linear projects list\n")

	return nil
}

func writeConfig(config ProjectConfig) error {
	data, err := yaml.Marshal(config)
	if err != nil {
		return err
	}

	header := "# Linear project configuration\n# Generated by 'linear init'\n\n"
	return os.WriteFile(configFileName, []byte(header+string(data)), 0644)
}

func appendToAgentFile(filename, teamKey string) error {
	content := generateAgentContent(teamKey)

	// Check if file exists
	existing, err := os.ReadFile(filename)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	// Check if the Linear section with this exact content already exists
	// Use a unique marker from the generated content to detect duplicates
	uniqueMarker := "This project uses **Linear** for issue tracking."
	if strings.Contains(string(existing), uniqueMarker) {
		// Already has Linear section with content, skip
		return nil
	}

	// Append to file
	f, err := os.OpenFile(filename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	// Add newlines if file has content
	if len(existing) > 0 && !strings.HasSuffix(string(existing), "\n\n") {
		if strings.HasSuffix(string(existing), "\n") {
			_, _ = f.WriteString("\n")
		} else {
			_, _ = f.WriteString("\n\n")
		}
	}

	_, err = f.WriteString(content)
	return err
}

func generateAgentContent(teamKey string) string {
	return fmt.Sprintf(`## Linear

This project uses **Linear** for issue tracking.
Default team: **%s**

### Creating Issues

`+"```bash"+`
# Create a simple issue
linear issues create "Fix login bug" --team %s --priority high

# Create with full details and dependencies
linear issues create "Add OAuth integration" \
  --team %s \
  --description "Integrate Google and GitHub OAuth providers" \
  --parent %s-100 \
  --depends-on %s-99 \
  --labels "backend,security" \
  --estimate 5

# List and view issues
linear issues list
linear issues get %s-123
`+"```"+`

### Fetching private Linear images

`+"`uploads.linear.app`"+` URLs in issue descriptions require authentication.
Do **NOT** use `+"`WebFetch`"+` or `+"`curl`"+` — they will 401.

`+"```bash"+`
linear attachments download "https://uploads.linear.app/..."
# → /tmp/linear-img-<hash>.png
`+"```"+`

Then `+"`Read`"+` that path to view the image.

### Claude Code Skills

Available workflow skills (install with `+"`linear skills install --all`"+`):
- `+"`/prd`"+` - Create agent-friendly tickets with PRDs and sub-issues
- `+"`/triage`"+` - Analyze and prioritize backlog
- `+"`/cycle-plan`"+` - Plan cycles using velocity analytics
- `+"`/retro`"+` - Generate sprint retrospectives
- `+"`/deps`"+` - Analyze dependency chains

Run `+"`linear skills list`"+` for details.
`, teamKey, teamKey, teamKey, teamKey, teamKey, teamKey)
}

// LoadProjectConfig loads the .linear.yaml config from current or parent directories
func LoadProjectConfig() (*ProjectConfig, error) {
	dir, err := os.Getwd()
	if err != nil {
		return nil, err
	}

	// Walk up directory tree looking for config
	for {
		configPath := filepath.Join(dir, configFileName)
		if _, err := os.Stat(configPath); err == nil {
			data, err := os.ReadFile(configPath)
			if err != nil {
				return nil, err
			}

			var cfg ProjectConfig
			if err := yaml.Unmarshal(data, &cfg); err != nil {
				return nil, err
			}
			return &cfg, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return nil, nil // No config found
}

// GetDefaultTeam returns the default team from config, or empty string
func GetDefaultTeam() string {
	config, err := LoadProjectConfig()
	if err != nil || config == nil {
		return ""
	}
	return config.Team
}

// GetDefaultProject returns the default project from config, or empty string
func GetDefaultProject() string {
	config, err := LoadProjectConfig()
	if err != nil || config == nil {
		return ""
	}
	return config.Project
}

// GetDefaultWorkspace returns the default workspace from config, or empty string.
// The special value "default" is normalized to "" (the unnamed default workspace).
func GetDefaultWorkspace() string {
	config, err := LoadProjectConfig()
	if err != nil || config == nil {
		return ""
	}
	if config.Workspace == "default" {
		return ""
	}
	return config.Workspace
}

// workspaceLabelForDefault returns a display label for the unnamed default workspace.
// If its token has org metadata, returns "centrum-ai (default)"; otherwise "(default)".
func workspaceLabelForDefault() string {
	path := token.GetWorkspaceTokenPath("")
	storage := token.NewStorage(path)
	if td, err := storage.LoadTokenData(); err == nil {
		if td.OrgURLKey != "" {
			return fmt.Sprintf("%s (default)", td.OrgURLKey)
		}
		if td.OrgName != "" {
			return fmt.Sprintf("%s (default)", td.OrgName)
		}
	}
	return "(default)"
}

// discoverWorkspaces returns a list of available workspace names by scanning
// token files on disk. Returns empty string for the default workspace.
// Uses the same approach as auth list/status for consistency.
func discoverWorkspaces() []string {
	tokens := token.ListWorkspaceTokens()
	workspaces := make([]string, 0, len(tokens))
	for _, wt := range tokens {
		workspaces = append(workspaces, wt.Name)
	}
	// ListWorkspaceTokens returns default ("") first, then named workspaces
	// in filesystem order; sort named ones for stable display.
	if len(workspaces) > 1 && workspaces[0] == "" {
		sort.Strings(workspaces[1:])
	} else {
		sort.Strings(workspaces)
	}
	return workspaces
}

// promptWorkspaceSelection displays a picker for workspace selection.
// Returns the selected workspace name (empty string for default).
func promptWorkspaceSelection(workspaces []string) string {
	fmt.Println("Available workspaces:")
	for i, w := range workspaces {
		if w == "" {
			label := workspaceLabelForDefault()
			fmt.Printf("  %d. %s\n", i+1, label)
		} else {
			fmt.Printf("  %d. %s\n", i+1, w)
		}
	}
	fmt.Println()

	fmt.Print("Select workspace [1]: ")
	reader := bufio.NewReader(os.Stdin)
	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(input)

	selection := 1
	if input != "" {
		sel, err := strconv.Atoi(input)
		if err != nil || sel < 1 || sel > len(workspaces) {
			fmt.Printf("Invalid selection, using default\n")
			return workspaces[0]
		}
		selection = sel
	}

	return workspaces[selection-1]
}
